"""
database.py - ChromaDB Vector Store Module

Manages the local ChromaDB persistent vector database.
Uses Ollama's nomic-embed-text model for embedding generation.
Implements Option B architecture: single collection with metadata tags
('person' or 'place') for cross-domain query support.
"""

import sys
import os

# Force UTF-8 output on Windows
if sys.platform == "win32":
    os.system("chcp 65001 >nul 2>&1")
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import shutil
import chromadb
import ollama
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn

console = Console(force_terminal=True)

# ─── Configuration ─────────────────────────────────────────────────────────────

CHROMA_DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chroma_db")
COLLECTION_NAME = "wiki_rag"
EMBEDDING_MODEL = "nomic-embed-text"
BATCH_SIZE = 50  # Number of documents to embed and insert at once


def get_chroma_client() -> chromadb.ClientAPI:
    """
    Initialize and return a persistent ChromaDB client.

    Returns:
        A ChromaDB PersistentClient pointing to the local chroma_db directory.
    """
    return chromadb.PersistentClient(path=CHROMA_DB_PATH)


def get_or_create_collection(client: chromadb.ClientAPI) -> chromadb.Collection:
    """
    Get or create the main wiki_rag collection with cosine similarity.

    Args:
        client: An initialized ChromaDB client.

    Returns:
        The wiki_rag collection.
    """
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
    )


def generate_embedding(text: str) -> list[float]:
    """
    Generate an embedding vector for a single text using Ollama's
    nomic-embed-text model.

    Args:
        text: The text to embed.

    Returns:
        A list of floats representing the embedding vector.
    """
    response = ollama.embed(model=EMBEDDING_MODEL, input=text)
    return response["embeddings"][0]


def generate_embeddings_batch(texts: list[str]) -> list[list[float]]:
    """
    Generate embedding vectors for a batch of texts using Ollama's
    nomic-embed-text model.

    Args:
        texts: A list of texts to embed.

    Returns:
        A list of embedding vectors.
    """
    response = ollama.embed(model=EMBEDDING_MODEL, input=texts)
    return response["embeddings"]


def store_chunks(chunks: list[dict]) -> int:
    """
    Embed and store all chunks in ChromaDB.

    Each chunk is stored with:
    - A unique ID (entity_name_chunk_index)
    - The text content as the document
    - Metadata: entity name and type (person/place)
    - The embedding vector generated by nomic-embed-text

    Args:
        chunks: List of chunk dicts from ingest.py with keys:
                'text', 'entity', 'type', 'chunk_index'.

    Returns:
        The total number of chunks stored.
    """
    client = get_chroma_client()
    collection = get_or_create_collection(client)

    total = len(chunks)
    console.print(f"\n[bold cyan]Storing {total} chunks in ChromaDB[/bold cyan]")
    console.print(f"   Embedding model: [bold]{EMBEDDING_MODEL}[/bold]")
    console.print(f"   Database path: [dim]{CHROMA_DB_PATH}[/dim]\n")

    stored = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("[cyan]Embedding & storing...", total=total)

        # Process in batches for efficiency
        for i in range(0, total, BATCH_SIZE):
            batch = chunks[i : i + BATCH_SIZE]

            ids = []
            documents = []
            metadatas = []
            texts_to_embed = []

            for chunk in batch:
                # Create a unique ID: sanitize entity name + chunk index
                entity_safe = chunk["entity"].replace(" ", "_").lower()
                chunk_id = f"{entity_safe}_{chunk['chunk_index']}"

                ids.append(chunk_id)
                documents.append(chunk["text"])
                metadatas.append({
                    "entity": chunk["entity"],
                    "type": chunk["type"],
                })
                texts_to_embed.append(chunk["text"])

            # Generate embeddings for the batch
            progress.update(task, description=f"[cyan]Embedding batch {i // BATCH_SIZE + 1}...")
            embeddings = generate_embeddings_batch(texts_to_embed)

            # Upsert into ChromaDB
            collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas,
                embeddings=embeddings,
            )

            stored += len(batch)
            progress.advance(task, advance=len(batch))

    console.print(f"\n[bold green]Successfully stored {stored} chunks in ChromaDB![/bold green]\n")
    return stored


def query_collection(
    query_text: str,
    n_results: int = 5,
    filter_type: str | None = None,
    entity_names: list[str] | None = None,
) -> dict:
    """
    Query the ChromaDB collection with a text query.

    Args:
        query_text: The user's search query.
        n_results: Number of top results to return.
        filter_type: Optional metadata filter -- 'person', 'place', or None for all.
        entity_names: Optional list of specific entity names to filter by.

    Returns:
        ChromaDB query results dict with keys: ids, documents, metadatas, distances.
    """
    client = get_chroma_client()
    collection = get_or_create_collection(client)

    # Generate query embedding
    query_embedding = generate_embedding(query_text)

    # Build where filter
    where_filter = None
    if entity_names and len(entity_names) == 1:
        # Single entity: simple filter
        where_filter = {"entity": entity_names[0]}
    elif entity_names and len(entity_names) > 1:
        # Multiple entities: use $or
        where_filter = {"$or": [{"entity": name} for name in entity_names]}
    elif filter_type in ("person", "place"):
        where_filter = {"type": filter_type}

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=n_results,
        where=where_filter,
        include=["documents", "metadatas", "distances"],
    )

    return results


def keyword_search_collection(
    keywords: list[str],
    n_results: int = 5,
    filter_type: str | None = None,
) -> dict:
    """
    Search the ChromaDB collection for documents containing specific keywords.
    Uses ChromaDB's where_document $contains filter for keyword matching.

    Args:
        keywords: List of keywords to search for in document text.
        n_results: Number of top results to return per keyword.
        filter_type: Optional metadata filter -- 'person', 'place', or None for all.

    Returns:
        ChromaDB get results dict with keys: ids, documents, metadatas.
    """
    client = get_chroma_client()
    collection = get_or_create_collection(client)

    # Build where filter
    where_filter = None
    if filter_type in ("person", "place"):
        where_filter = {"type": filter_type}

    all_ids = []
    all_docs = []
    all_metas = []
    seen_ids = set()

    for keyword in keywords:
        try:
            results = collection.get(
                where=where_filter,
                where_document={"$contains": keyword},
                include=["documents", "metadatas"],
                limit=n_results,
            )
            for doc_id, doc, meta in zip(results["ids"], results["documents"], results["metadatas"]):
                if doc_id not in seen_ids:
                    seen_ids.add(doc_id)
                    all_ids.append(doc_id)
                    all_docs.append(doc)
                    all_metas.append(meta)
        except Exception:
            continue

    return {
        "ids": all_ids,
        "documents": all_docs,
        "metadatas": all_metas,
    }


def get_collection_stats() -> dict:
    """
    Get statistics about the current ChromaDB collection.

    Returns:
        A dict with 'total_chunks', 'people_chunks', 'places_chunks'.
    """
    client = get_chroma_client()
    try:
        collection = client.get_collection(name=COLLECTION_NAME)
        total = collection.count()

        # Count by type
        people_results = collection.get(where={"type": "person"}, include=[])
        places_results = collection.get(where={"type": "place"}, include=[])

        return {
            "total_chunks": total,
            "people_chunks": len(people_results["ids"]),
            "places_chunks": len(places_results["ids"]),
        }
    except Exception:
        return {
            "total_chunks": 0,
            "people_chunks": 0,
            "places_chunks": 0,
        }


def clear_database() -> bool:
    """
    Delete the entire ChromaDB database directory and reset the system.

    Returns:
        True if the database was cleared successfully, False otherwise.
    """
    try:
        if os.path.exists(CHROMA_DB_PATH):
            shutil.rmtree(CHROMA_DB_PATH)
            console.print("[bold green]Database cleared successfully![/bold green]")
            return True
        else:
            console.print("[yellow]No database found to clear.[/yellow]")
            return True
    except Exception as e:
        console.print(f"[bold red]Error clearing database: {e}[/bold red]")
        return False


if __name__ == "__main__":
    stats = get_collection_stats()
    print(f"Database stats: {stats}")
